baseURL = "https://CSpotGo.github.io/"
languageCode = "en-us"
title = "CSpotGo"
theme="cactus"
colortheme="white"
description="A new site for me to learn."
mainSection = "posts"
showAllPostsOnHomePage = false
postsOnHomePage = 5

showProjectsList = true
projectsUrl = "https://github.com/monkeyWzr"

[[params.social]]
  name = "github"
  link = "https://github.com/TungPhung"

[[params.social]]
  name = "email"
  link = "ttp2d@virginia.edu" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/tung"

[[params.social]]
  name = "medium"
  link = "https://medium.com/@Tungy"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
